FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY module_c_notify.py .
COPY database/ ./database/

EXPOSE 5003

CMD ["python", "module_c_notify.py"]
