FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY module_b_tracking.py .
COPY database/ ./database/

EXPOSE 5002

CMD ["python", "module_b_tracking.py"]
